-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Create procedure basic template
-- =============================================
IF EXISTS (	SELECT name 
			FROM sysobjects
			WHERE  name = 'web_spU_ActualizarSolicitudPrestamo' AND
			TYPE = 'P')
	DROP PROCEDURE web_spU_ActualizarSolicitudPrestamo
GO
-- =============================================
-- Author:		Orlando Esparza
-- Create date: Lunes 20 de Abril de 2015
-- Description:	Actualizar un registro de Solicitud de préstamo por su ID
-- =============================================
CREATE PROCEDURE web_spU_ActualizarSolicitudPrestamo
	-- Add the parameters for the stored procedure here
	@ID							CHAR(8),
	@Cliente					CHAR(8),
	@Nacionalidad				VARCHAR(20),
	@NumeroDependientes			TINYINT,
	@Edades						VARCHAR(10),
	@RegistroMatrimonial		VARCHAR(50),
	@TipoCasa					VARCHAR(50),
	@AniosDomicilio				TINYINT,
	@CalleAnterior				VARCHAR(100),
	@NoExteriorAnterior			VARCHAR(10),
	@NoInteriorAnterior			VARCHAR(10),
	@ColoniaAnterior			CHAR(10),
	@CodigoPostalAnterior		INT,
	@EntreCallesAnterior		VARCHAR(100),
	@EstadoAnterior				CHAR(2),
	@MunicipioAnterior			CHAR(4),
	@Antiguedad					TINYINT,
	@Ingresos					SMALLINT,
	@OtrosIngresos				SMALLINT,
	@Concepto					VARCHAR(100),
	@JefeNombre					VARCHAR(50),
	@JefeAPAterno				VARCHAR(50),
	@JefeAMaterno				VARCHAR(50),
	@EmpresaAnterior			VARCHAR(50),
	@ConyugeNombre				VARCHAR(50),
	@ConyugeAPaterno			VARCHAR(50),
	@ConyugeAMaterno			VARCHAR(50),
	@ConyugeFechaNacimiento		DATE,
	@ConyugeEdad				TINYINT,
	@ConyugeRFC					VARCHAR(15),
	@ConyugeTelefono			VARCHAR(15),
	@ConyugeTelefonoMovil		VARCHAR(19),
	@ConyugeCalle				VARCHAR(100),
	@ConyugeEntreCalles			VARCHAR(100),
	@ConyugeNoExterior			VARCHAR(10),
	@ConyugeNoInterior			VARCHAR(10),
	@ConyugeColonia				CHAR(10),
	@ConyugeCodigoPostal		INT,
	@ConyugeEstado				CHAR(2),
	@ConyugeMunicipio			CHAR(4),
	@ConyugeAntiguedad			TINYINT,
	@ConyugeIngresos			SMALLINT,
	@ConyugeOtrosIngresos		SMALLINT,
	@ConyugeConcepto			VARCHAR(100),
	@ConyugeEmpresa				VARCHAR(50),
	@ConyugePuesto				VARCHAR(50),
	@ConyugeEmpresaCalle		VARCHAR(100),
	@ConyugeEmpresaNoExterior	VARCHAR(10),
	@ConyugeEmpresaNoInterior	VARCHAR(10),
	@ConyugeEmpresaColonia		CHAR(10),
	@ConyugeEmpresaCodigoPostal	INT,
	@ConyugeEmpresaEntreCalles	VARCHAR(100),
	@ConyugeEmpresaEstado		CHAR(2),
	@ConyugeEmpresaMunicipio	CHAR(4),
	@ConyugeEmpresaJefeNombre	VARCHAR(50),
	@ConyugeEmpresaJefeAPaterno	VARCHAR(50),
	@ConyugeEmpresaJefeAMaterno	VARCHAR(50),
	@AvalNombre					VARCHAR(50),
	@AvalAPaterno				VARCHAR(50),
	@AvalAMaterno				VARCHAR(50),
	@AvalSocio					BIT,
	@AvalEstadoCivil			VARCHAR(10),
	@AvalRegistroMatrimonial	VARCHAR(50),
	@AvalTelefono				VARCHAR(15),
	@AvalTelefonoMovil			VARCHAR(19),
	@AvalCalle					VARCHAR(100),
	@AvalEntreCalles			VARCHAR(100),
	@AvalNoExterior				VARCHAR(10),
	@AvalNoInterior				VARCHAR(10),
	@AvalColonia				CHAR(10),
	@AvalCodigoPostal			INT,
	@AvalEstado					CHAR(2),
	@AvalMunicipio				CHAR(4),
	@AvalTipoCasa				VARCHAR(20),
	@AvalAntiguedad				TINYINT,
	@AvalEmpresa				VARCHAR(50),
	@AvalEmpresaPuesto			VARCHAR(50),
	@AvalEmpresaJefeNombre		VARCHAR(50),
	@AvalEmpresaJefeAPaterno	VARCHAR(50),
	@AvalEmpresaJefeAMaterno	VARCHAR(50),
	@AvalEmpresaAntiguedad		TINYINT,
	@AvalEmpresaIngresos		INT,
	@AvalEmpresaOtrosIngresos	INT,
	@AvalEmpresaConcepto		VARCHAR(50),
	@AvalEmpresaPropietario		BIT,
	@AvalEmpresaTipo			VARCHAR(20),
	@AvalEmpresaTelefono		VARCHAR(15),
	@AvalEmpresaTelefonoExt		SMALLINT,
	@AvalEmpresaAnterior		VARCHAR(50),
	@Cantidad					INT,
	@Plazo						SMALLINT,
	@FormaPago					VARCHAR(20),
	@DestinoPrestamo			VARCHAR(50),
	@Tipo						VARCHAR(30),
	@TablaAmortizacion			VARCHAR(200),
	@Estatus					VARCHAR(20),
	@UsuarioModificacion		VARCHAR(50),
	@FechaModificacion			SMALLDATETIME
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
    UPDATE
		SolicitudesPrestamos
	SET
		Cliente = @Cliente,
		Nacionalidad = @Nacionalidad,
		NumeroDependientes = @NumeroDependientes,
		Edades = @Edades,
		RegistroMatrimonial = @RegistroMatrimonial,
		TipoCasa = @TipoCasa,
		AniosDomicilio = @AniosDomicilio,
		CalleAnterior = @CalleAnterior,
		NoExteriorAnterior = @NoExteriorAnterior,
		NoInteriorAnterior = @NoInteriorAnterior,
		ColoniaAnterior = @ColoniaAnterior,
		CodigoPostalAnterior = @CodigoPostalAnterior,
		EntreCallesAnterior = @EntreCallesAnterior,
		EstadoAnterior = @EstadoAnterior,
		MunicipioAnterior = @MunicipioAnterior,
		Antiguedad = @Antiguedad,
		Ingresos = @Ingresos,
		OtrosIngresos = @OtrosIngresos,
		Concepto = @Concepto,
		JefeNombre = @JefeNombre,
		JefeAPaterno = @JefeAPaterno,
		JefeAMaterno = @JefeAMaterno,
		EmpresaAnterior = @EmpresaAnterior,
		ConyugeNombre = @ConyugeNombre,
		ConyugeAPaterno = @ConyugeAPaterno,
		ConyugeAMaterno = @ConyugeAMaterno,
		ConyugeFechaNacimiento = @ConyugeFechaNacimiento,
		ConyugeEdad = @ConyugeEdad,
		ConyugeRFC = @ConyugeRFC,
		ConyugeTelefono = @ConyugeTelefono,
		ConyugeTelefonoMovil = @ConyugeTelefonoMovil,
		ConyugeCalle = @ConyugeCalle,
		ConyugeEntreCalles = @ConyugeEntreCalles,
		ConyugeNoExterior = @ConyugeNoExterior,
		ConyugeNoInterior = @ConyugeNoInterior,
		ConyugeColonia = @ConyugeColonia,
		ConyugeCodigoPostal = @ConyugeCodigoPostal,
		ConyugeEstado = @ConyugeEstado,
		ConyugeMunicipio = @ConyugeMunicipio,
		ConyugeAntiguedad = @ConyugeAntiguedad,
		ConyugeIngresos = @ConyugeIngresos,
		ConyugeOtrosIngresos = @ConyugeOtrosIngresos,
		ConyugeConcepto = @ConyugeConcepto,
		ConyugeEmpresa = @ConyugeEmpresa,
		ConyugePuesto = @ConyugePuesto,
		ConyugeEmpresaCalle = @ConyugeEmpresaCalle,
		ConyugeEmpresaNoExterior = @ConyugeEmpresaNoExterior,
		ConyugeEmpresaNoInterior = @ConyugeEmpresaNoInterior,
		ConyugeEmpresaColonia = @ConyugeEmpresaColonia,
		ConyugeEmpresaCodigoPostal = @ConyugeEmpresaCodigoPostal,
		ConyugeEmpresaEntreCalles = @ConyugeEmpresaEntreCalles,
		ConyugeEmpresaEstado = @ConyugeEmpresaEstado,
		ConyugeEmpresaMunicipio = @ConyugeEmpresaMunicipio,
		ConyugeEmpresaJefeNombre = @ConyugeEmpresaJefeNombre,
		ConyugeEmpresaJefeAPaterno = @ConyugeEmpresaJefeAPaterno,
		ConyugeEmpresaJefeAMaterno = @ConyugeEmpresaJefeAMaterno,
		AvalNombre = @AvalNombre,
		AvalAPaterno = @AvalAPaterno,
		AvalAMaterno = @AvalAMaterno,
		AvalSocio = @AvalSocio,
		AvalEstadoCivil = @AvalEstadoCivil,
		AvalRegistroMatrimonial = @AvalRegistroMatrimonial,
		AvalTelefono = @AvalTelefono,
		AvalTelefonoMovil = @AvalTelefonoMovil,
		AvalCalle = @AvalCalle,
		AvalEntreCalles = @AvalEntreCalles,
		AvalNoExterior = @AvalNoExterior,
		AvalNoInterior = @AvalNoInterior,
		AvalColonia = @AvalColonia,
		AvalCodigoPostal = @AvalCodigoPostal,
		AvalEstado = @AvalEstado,
		AvalMunicipio = @AvalMunicipio,
		AvalTipoCasa = @AvalTipoCasa,
		AvalAntiguedad = @AvalAntiguedad,
		AvalEmpresa = @AvalEmpresa,
		AvalEmpresaPuesto = @AvalEmpresaPuesto,
		AvalEmpresaJefeNombre = @AvalEmpresaJefeNombre,
		AvalEmpresaJefeAPaterno = @AvalEmpresaJefeAPaterno,
		AvalEmpresaJefeAMaterno = @AvalEmpresaJefeAMaterno,
		AvalEmpresaAntiguedad = @AvalEmpresaAntiguedad,
		AvalEmpresaIngresos = @AvalEmpresaIngresos,
		AvalEmpresaOtrosIngresos = @AvalEmpresaOtrosIngresos,
		AvalEmpresaConcepto = @AvalEmpresaConcepto,
		AvalEmpresaPropietario = @AvalEmpresaPropietario,
		AvalEmpresaTipo = @AvalEmpresaTipo,
		AvalEmpresaTelefono = @AvalEmpresaTelefono,
		AvalEmpresaTelefonoExt = @AvalEmpresaTelefonoExt,
		AvalEmpresaAnterior = @AvalEmpresaAnterior,
		Cantidad = @Cantidad,
		Plazo = @Plazo,
		FormaPago = @FormaPago,
		DestinoPrestamo = @DestinoPrestamo,
		Tipo = @Tipo,
		TablaAmortizacion = @TablaAmortizacion,
		Estatus = @Estatus,
		UsuarioModificacion = @UsuarioModificacion,
		FechaModificacion = @FechaModificacion
	WHERE
		ID = @ID
END
GO